services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: speedtest-api
    environment:
      PORT: 3000
      NODE_ENV: production
    ports:
      - "${API_PORT:-3010}:3000"
    restart: always


  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3010}
        - NEXT_PUBLIC_ENGINE_URL=${NEXT_PUBLIC_ENGINE_URL:-http://localhost:3010}
    container_name: speedtest-web
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3010}
      NEXT_PUBLIC_ENGINE_URL: ${NEXT_PUBLIC_ENGINE_URL:-http://localhost:3010}
    ports:
      - "${WEB_PORT:-3011}:3000"
    depends_on:
      - api
    restart: always
